"""update Class table

Revision ID: 28018a8cce68
Revises: e81ae8ef47ef
Create Date: 2026-09-25 23:05:42.671414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28018a8cce68'
down_revision: Union[str, Sequence[str], None] = 'e81ae8ef47ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('class', sa.Column('course_number', sa.Integer(), nullable=False))
    op.add_column('class', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('class', 'class_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('class', 'department')
    op.drop_column('class', 'course_number')
    op.drop_column('class', 'type')
    # ### end Alembic commands ###
