"""add_token_version to user

Revision ID: 5c094a3746cd
Revises: b84fab4ca5ff
Create Date: 2026-09-13 13:37:30.641872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c094a3746cd'
down_revision: Union[str, Sequence[str], None] = 'b84fab4ca5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_version')
    # ### end Alembic commands ###
