"""create initial tables

Revision ID: b84fab4ca5ff
Revises: 
Create Date: 2026-09-10 15:07:48.572759

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b84fab4ca5ff'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('course',
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_number_student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('enrollment',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_number_assignment', sa.Integer(), nullable=False),
    sa.Column('total_number_student_finished', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('problem',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('start_format_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('complexity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('total_number_testcase', sa.Integer(), nullable=False),
    sa.Column('report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_table('submission',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compile_output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('submitted_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('testcase',
    sa.Column('testcase_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('input_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_output_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.PrimaryKeyConstraint('testcase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testcase')
    op.drop_table('submission')
    op.drop_table('problem')
    op.drop_table('lesson')
    op.drop_table('enrollment')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
