"""add class table and add class_id to user

Revision ID: e81ae8ef47ef
Revises: 8b2c3d4e5f6a
Create Date: 2026-09-22 23:46:29.505559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e81ae8ef47ef'
down_revision: Union[str, Sequence[str], None] = '8b2c3d4e5f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.add_column('user', sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_foreign_key('fk_user_class_id_class', 'user', 'class', ['class_id'], ['class_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_class_id_class', 'user', type_='foreignkey')
    op.drop_column('user', 'class_id')
    op.drop_table('class')
    # ### end Alembic commands ###
